project:
  type: website

website:
  title: "My Gapminder Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: life-gdp.qmd
        text: "Life & GDP"
      - href: life-population.qmd
        text: "Life & Population"
      - href: country.qmd
        text: "Country Analysis"
      - about.qmd

output-dir: docs

format:
  html:
    theme:
      - cerulean
    css: styles.css
    toc: true